import { ArrowUpRight } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import Layout from '@/components/common/Layout';
import { events, projects, siteSettings } from '@/data/site-content';

export default function Home() {
  const selectedEvents = events.slice(0, 3);
  const selectedProjects = projects.slice(0, 3);
  return <Layout><Helmet><title>DevCatalyst — A student community creating real opportunities</title><meta name="description" content="DevCatalyst is a student community creating real opportunities through workshops, projects, hackathons, and collaboration." /></Helmet>
    <section className="relative isolate overflow-hidden border-b border-[#dedcd5] px-5 pb-24 pt-28 sm:px-8 sm:pb-32 sm:pt-40 lg:px-10"><span className="figure right-[10%] top-28 h-20 w-20 rounded-full" /><span className="figure left-[7%] top-[62%] h-4 w-4 rotate-45" /><span className="figure-dot right-[21%] top-[65%]" /><span className="figure left-[76%] top-[25%] h-3 w-10" /><div className="relative mx-auto max-w-7xl"><p className="eyebrow">Student-led · Hyderabad</p><h1 className="page-title mt-8 max-w-6xl">DEV<span className="text-[#2455c9]">/</span>CATALYST</h1><p className="editorial-serif mt-10 max-w-2xl text-3xl leading-[.98] tracking-[-.045em] text-[#15171b] sm:text-5xl">A student community creating real opportunities.</p><p className="mt-6 max-w-lg text-base leading-7 text-[#5c616a]">Student-led. Builder-minded. Connected to ideas, people, and opportunities worth pursuing.</p></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 border-b border-[#dedcd5] pb-20 lg:grid-cols-[.9fr_1.1fr]"><div><p className="eyebrow">Why DevCatalyst</p><h2 className="section-title mt-5">A place to find your people and move your ideas forward.</h2></div><div className="max-w-xl self-end space-y-5 text-lg leading-8 text-[#5c616a]"><p>DevCatalyst brings together students who want to learn in public, build with others, and discover opportunities that are difficult to reach alone.</p><p>We make room for useful conversations, practical work, and the momentum that turns an early idea into something real.</p></div></div></section>

    <section className="px-5 pb-24 sm:px-8 sm:pb-32 lg:px-10"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-x-6 gap-y-10 border-b border-[#dedcd5] pb-20 sm:grid-cols-5">{siteSettings.stats.map(([value, label]) => <div key={label}><p className="editorial-serif text-4xl tracking-[-.05em] sm:text-5xl">{value}</p><p className="mt-2 text-xs font-bold uppercase tracking-[.12em] text-[#5c616a]">{label}</p></div>)}</div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-7xl"><p className="eyebrow">Opportunities in motion</p><div className="mt-12 divide-y divide-[#dedcd5] border-y border-[#dedcd5]">{[['01', 'Learn together', 'Workshops, talks, and hands-on sessions that leave students with something useful.'], ['02', 'Build in public', 'Projects, hackathons, and practical collaboration with people who care about the work.'], ['03', 'Find opportunity', 'Peers, partners, mentors, and doors worth opening.']].map(([number, title, copy]) => <div key={number} className="grid gap-4 py-8 sm:grid-cols-[6rem_1fr_1fr] sm:items-start"><p className="text-sm font-extrabold text-[#2455c9]">{number}</p><h3 className="editorial-serif text-3xl tracking-[-.04em]">{title}</h3><p className="max-w-md leading-7 text-[#5c616a]">{copy}</p></div>)}</div></div></section>

    <section className="bg-[#e7eeff] px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 border-b border-[#b9caef] pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow">Recent moments</p><h2 className="section-title mt-5">Work that brought people together.</h2></div><Link className="text-link" to="/events">View all events <ArrowUpRight size={16} /></Link></div><div className="mt-8 divide-y divide-[#b9caef]">{selectedEvents.map((event) => <Link key={event.id} to="/events" className="grid gap-3 py-6 transition hover:pl-2 sm:grid-cols-[1.15fr_.75fr_.5fr]"><h3 className="editorial-serif text-3xl tracking-[-.04em]">{event.title}</h3><p className="text-sm leading-6 text-[#5c616a]">{event.outcome}</p><p className="text-sm font-bold text-[#5c616a]">{event.category}<br />{event.date}</p></Link>)}</div></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 border-b border-[#dedcd5] pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow">Selected projects</p><h2 className="section-title mt-5">Ideas made real.</h2></div><Link className="text-link" to="/projects">View all projects <ArrowUpRight size={16} /></Link></div><div className="divide-y divide-[#dedcd5]">{selectedProjects.map((project) => <Link key={project.id} to="/projects" className="grid gap-3 py-7 sm:grid-cols-[1fr_.8fr_.55fr]"><h3 className="editorial-serif text-3xl tracking-[-.04em]">{project.title}</h3><p className="leading-7 text-[#5c616a]">{project.description}</p><p className="text-sm font-bold text-[#5c616a]">{project.area}<br />{project.creators}</p></Link>)}</div></div></section>

    <section className="border-y border-[#dedcd5] px-5 py-16 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><p className="eyebrow">Alongside</p><p className="editorial-serif mt-5 max-w-3xl text-3xl leading-[.98] tracking-[-.045em] sm:text-5xl">People and communities who believe students should have access to more.</p><div className="mt-12 flex flex-wrap gap-x-10 gap-y-5 text-lg font-extrabold tracking-[-.04em] text-[#5c616a]">{siteSettings.partners.map((partner) => <span key={partner}>{partner}</span>)}</div></div></section>

    <section className="px-5 py-24 sm:px-8 sm:py-32 lg:px-10"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">Join the community</p><h2 className="section-title mt-5">The work matters. The people you build it with matter more.</h2></div><div className="self-end"><p className="max-w-md text-lg leading-8 text-[#5c616a]">Meet builders, find out what is happening, and take part in what comes next.</p><a className="solid-action mt-8" href={siteSettings.whatsappUrl} target="_blank" rel="noreferrer">Join the WhatsApp community <ArrowUpRight size={16} /></a></div></div></section>
  </Layout>;
}
