import { useEffect, useState, type FormEvent } from 'react';
import { Helmet } from 'react-helmet-async';
import { ArrowUpRight, Lock, LogOut } from 'lucide-react';

type SessionState = 'checking' | 'signed-out' | 'signed-in';

export default function Admin() {
  const [session, setSession] = useState<SessionState>('checking');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  useEffect(() => { fetch('/api/admin-auth').then((response) => response.ok ? setSession('signed-in') : setSession('signed-out')).catch(() => setSession('signed-out')); }, []);
  const signIn = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSubmitting(true); setError(null); try { const response = await fetch('/api/admin-auth', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) }); if (!response.ok) throw new Error('Incorrect password.'); setPassword(''); setSession('signed-in'); } catch (authError) { setError(authError instanceof Error ? authError.message : 'Unable to sign in.'); } finally { setIsSubmitting(false); } };
  const signOut = async () => { await fetch('/api/admin-auth', { method: 'DELETE' }); setSession('signed-out'); };
  return <main className="min-h-screen bg-[#15171b] px-5 py-8 text-[#f7f6f2] sm:px-8 lg:px-10"><Helmet><title>Admin — DevCatalyst</title></Helmet><div className="mx-auto max-w-6xl">{session === 'checking' ? <p className="text-sm text-white/60">Checking session…</p> : session === 'signed-out' ? <section className="mx-auto mt-[18vh] max-w-md"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#9bb7ff]">DevCatalyst admin</p><h1 className="editorial-serif mt-5 text-5xl tracking-[-.06em]">Welcome back.</h1><p className="mt-4 leading-7 text-white/65">Use the organiser password to manage the living parts of the site.</p><form onSubmit={signIn} className="mt-9 grid gap-4"><label className="grid gap-2 text-sm font-bold">Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" required className="border border-white/25 bg-transparent px-4 py-3 outline-none focus:border-[#9bb7ff]" /></label>{error && <p className="text-sm font-semibold text-red-300">{error}</p>}<button disabled={isSubmitting} className="inline-flex w-fit items-center gap-2 bg-[#f7f6f2] px-4 py-3 text-xs font-extrabold uppercase tracking-[.08em] text-[#15171b] disabled:opacity-50" type="submit"><Lock size={15} />{isSubmitting ? 'Signing in…' : 'Sign in'}</button></form></section> : <section><header className="flex items-center justify-between border-b border-white/15 pb-6"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#9bb7ff]">DevCatalyst admin</p><h1 className="editorial-serif mt-3 text-5xl tracking-[-.06em]">Overview</h1></div><button onClick={signOut} className="inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.08em] text-white/70 hover:text-white"><LogOut size={15} /> Sign out</button></header><div className="mt-12 grid gap-px border border-white/15 bg-white/15 sm:grid-cols-2 lg:grid-cols-3">{[['Events', 'Create active and completed events, Drive images, categories, and gallery stories.'], ['Projects', 'Maintain titles, makers, links, and display order.'], ['Team', 'Publish current organiser profiles and photos.'], ['Partners', 'Manage official partner names and logo assets.'], ['Homepage', 'Control stats, featured content, and the final WhatsApp action.'], ['Site settings', 'Update the WhatsApp community URL and contact details.']].map(([title, detail]) => <div key={title} className="bg-[#15171b] p-7"><h2 className="editorial-serif text-3xl tracking-[-.045em]">{title}</h2><p className="mt-4 leading-7 text-white/60">{detail}</p><span className="mt-8 inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.08em] text-[#9bb7ff]">Content connection next <ArrowUpRight size={14} /></span></div>)}</div></section>}</div></main>;
}
